[versions]
aescrypt = "0.0.1"
agp = "8.8.0"
androidDatabaseSqlcipher = "4.5.4"
cameraCamera2 = "1.2.0-alpha04"
faceDetection = "16.1.7"
ffmpegKitFull = "6.0-2"
gson = "2.10.1"
http = "20070405"
javaAndroidWebsocketClient = "1.2.2"
json = "20230618"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
media3Effect = "1.6.0"
media3Exoplayer = "1.5.1"
media3Transformer = "1.6.0"
navigationCompose = "2.8.6"
playServicesLocation = "21.3.0"
smartExceptionJava = "0.2.1"
sqlite = "2.4.0"
tensorflowCorePlatform = "1.0.0"
tensorflowLite = "2.9.0"
tensorflowLiteTaskVision = "0.3.1"
volley = "1.2.1"
navigationRuntime = "2.8.6"
navigationUi = "2.8.6"
navigationFragment = "2.8.6"
media3ExoplayerHls = "1.5.1"
media3ExoplayerRtsp = "1.6.0"
media3ExoplayerMediacodec = "1.5.1"
playServicesVisionCommon = "19.1.3"
preference = "1.2.1"

[libraries]
aescrypt = { module = "com.scottyab:aescrypt", version.ref = "aescrypt" }
android-database-sqlcipher = { module = "net.zetetic:android-database-sqlcipher", version.ref = "androidDatabaseSqlcipher" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraCamera2" }
androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "cameraCamera2" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraCamera2" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraCamera2" }
androidx-media3-cast = { module = "androidx.media3:media3-cast", version.ref = "media3Effect" }
androidx-media3-common = { module = "androidx.media3:media3-common", version.ref = "media3Exoplayer" }
androidx-media3-container = { module = "androidx.media3:media3-container", version.ref = "media3Effect" }
androidx-media3-datasource-okhttp = { module = "androidx.media3:media3-datasource-okhttp", version.ref = "media3ExoplayerRtsp" }
androidx-media3-effect = { module = "androidx.media3:media3-effect", version.ref = "media3Exoplayer" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Exoplayer" }
androidx-media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3Exoplayer" }
androidx-media3-exoplayer-smoothstreaming = { module = "androidx.media3:media3-exoplayer-smoothstreaming", version.ref = "media3ExoplayerRtsp" }
androidx-media3-extractor = { module = "androidx.media3:media3-extractor", version.ref = "media3ExoplayerRtsp" }
androidx-media3-muxer = { module = "androidx.media3:media3-muxer", version.ref = "media3Exoplayer" }
androidx-media3-transformer = { module = "androidx.media3:media3-transformer", version.ref = "media3Exoplayer" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3Exoplayer" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-navigation-dynamic-features-fragment = { module = "androidx.navigation:navigation-dynamic-features-fragment", version.ref = "navigationCompose" }
androidx-navigation-testing = { module = "androidx.navigation:navigation-testing", version.ref = "navigationCompose" }
face-detection = { module = "com.google.mlkit:face-detection", version.ref = "faceDetection" }
ffmpeg-kit-full = { module = "com.arthenica:ffmpeg-kit-full-gpl", version.ref = "ffmpegKitFull" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
http = { module = "com.sun.net.httpserver:http", version.ref = "http" }
java-android-websocket-client = { module = "tech.gusavila92:java-android-websocket-client", version.ref = "javaAndroidWebsocketClient" }
json = { module = "org.json:json", version.ref = "json" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
smart-exception-java = { module = "com.arthenica:smart-exception-java", version.ref = "smartExceptionJava" }
sqlite = { module = "androidx.sqlite:sqlite", version.ref = "sqlite" }

tensorflow-core-platform = { group = "org.tensorflow", name = "tensorflow-core-platform", version.ref = "tensorflowCorePlatform" }
tensorflow-lite = { module = "org.tensorflow:tensorflow-lite", version.ref = "tensorflowLite" }
tensorflow-lite-gpu = { module = "org.tensorflow:tensorflow-lite-gpu", version.ref = "tensorflowLite" }
tensorflow-lite-task-vision = { module = "org.tensorflow:tensorflow-lite-task-vision", version.ref = "tensorflowLiteTaskVision" }
volley = { module = "com.android.volley:volley", version.ref = "volley" }
navigation-runtime = { group = "androidx.navigation", name = "navigation-runtime", version.ref = "navigationRuntime" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
androidx-media3-exoplayer-hls = { group = "androidx.media3", name = "media3-exoplayer-hls", version.ref = "media3ExoplayerHls" }
androidx-media3-exoplayer-rtsp = { group = "androidx.media3", name = "media3-exoplayer-rtsp", version.ref = "media3ExoplayerRtsp" }

play-services-vision-common = { group = "com.google.android.gms", name = "play-services-vision-common", version.ref = "playServicesVisionCommon" }
androidx-preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

